manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: dhruvinsh
      url-base: https://github.com/dhruvinsh
    - name: MickiusMousius
      url-base: https://github.com/MickiusMousius
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 773dec58eaacaef4703b3e4595e50bd71f6cad3d
      import: app/west.yml
    - name: zmk-tri-state
      remote: dhruvinsh
      revision: main
      clone-depth: 1
    - name: zmk-ls0xxvcom-driver
      remote: MickiusMousius
      revision: main
      clone-depth: 1
  self:
    path: config
